const SituacaoReserva = Object.freeze({
  APROVADO: 'APROVADO',
  CONCLUIDO: 'CONCLUIDO',
  CANCELADO: 'CANCELADO',
  ANDAMENTO: 'ANDAMENTO',
  AGUARDANDO_PAGAMENTO: 'AGUARDANDO_PAGAMENTO',
  ADIADO: 'ADIADO',
  AGUARDANDO_ACEITACAO: 'AGUARDANDO_ACEITACAO',
  CANCELADO_COM_CREDITO: 'CANCELADO_COM_CREDITO',
  CREDITO: 'CREDITO'
});

module.exports = SituacaoReserva;
