const SituacaoReserva = Object.freeze({
  APROVADO: 'APROVADO', // APROVADA
  CONCLUIDO: 'CONCLUIDO', // CONCLUIDA
  CANCELADO: 'CANCELADO', // CANCELADA
  ANDAMENTO: 'ANDAMENTO', // EM_USO
  AGUARDANDO_PAGAMENTO: 'AGUARDANDO_PAGAMENTO', // PENDENTE_PAGAMENTO
  AGUARDANDO_ACEITACAO: 'AGUARDANDO_ACEITACAO', // PENDENTE_APROVACAO
  CANCELADO_COM_CREDITO: 'CANCELADO_COM_CREDITO', // CANCELADA_COM_CREDITO
});

module.exports = SituacaoReserva;
